//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_management_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public string S_ID { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> day_total { get; set; }
        public Nullable<int> month_total { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
