//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_management_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_view
    {
        public string dID { get; set; }
        public Nullable<int> buyingPrice { get; set; }
        public string Drink_Name { get; set; }
        public Nullable<int> amount { get; set; }
        public string Supplier_ID { get; set; }
    }
}
