//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_management_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_pay
    {
        public string E_ID { get; set; }
        public System.DateTime month { get; set; }
        public Nullable<int> days_absent { get; set; }
        public Nullable<int> penalty { get; set; }
        public Nullable<int> total_salary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
