//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_management_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class working
    {
        public string E_ID { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public string Name { get; set; }
        public string position { get; set; }
        public Nullable<int> fixed_salary { get; set; }
        public string email { get; set; }
        public Nullable<int> phone_number { get; set; }
        public string status { get; set; }
    }
}
